language: node_js

node_js:
  - "stable"

branches:
  only:
    - prod

before_install:
  - npm i -g npm@latest
  - npm i

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng build

